apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-slave
  namespace: lrd-bigdata
  labels:
    name: mysql-slave
spec:
  replicas: 1
  selector:
    name: mysql-slave
  template:
    metadata:
      labels:
        name: mysql-slave
    spec:
      containers:
        - name: mysql-slave
          image: 18800172152/mysql-slave:sdr-1
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-slave-data
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "sddt8888"
            - name: MYSQL_REPLICATION_USER
              value: "root"
            - name: MYSQL_REPLICATION_PASSWORD
              value: "sddt8888"
            - name: MYSQL_MASTER_SERVICE_HOST
              value: 10.10.202.140
      volumes:
        - name: mysql-slave-data
          persistentVolumeClaim:
            claimName: pv-nfs-mysql-slave
      nodeSelector:
        lrd-node-type: bigdata

