apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql-slave
  namespace: lrd-bigdata
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/data/mysql_slave
    server: 192.168.188.82
  persistentVolumeReclaimPolicy: Recycle

---
# cat nfs-pvc-slave.yaml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-nfs-mysql-slave
  namespace: lrd-bigdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
