apiVersion: v1
kind: Service
metadata:
  name: flink-web-service
spec:
  selector:
    app: flink
    type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30123
    clusterIP: 10.10.230.179