apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-mysql-pv
spec:
  capacity:
    storage: 50Gi      #磁盘大小50Gi
  accessModes:
    - ReadWriteOnce    #单客户可读写
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "mysql-cluster"
  nfs:
    server: 192.168.188.91
    path: "/home/nfsdata/mysql_m"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-mysql-pv-2
spec:
  capacity:
    storage: 50Gi      #磁盘大小50Gi
  accessModes:
    - ReadWriteOnce    #单客户可读写
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "mysql-cluster"
  nfs:
    server: 192.168.188.93
    path: "/home/nfsdata/mysql_s"
	
	
	
	
	