apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-client
spec:
  nodeSelector:
    kubernetes.io/hostname: node83
  containers:
    - command:
        - sh
        - -c
        - exec tail -f /dev/null
      image: registry.cn-shanghai.aliyuncs.com/zhangdongsheng/kafka-k8s:2.0
      imagePullPolicy: IfNotPresent
      name: kafka
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
# 测试使用, 可以在这个pod上用命令测试kafka
