apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-kafka1
spec:
  capacity:
    storage: 50Gi      #磁盘大小50Gi
  accessModes:
    - ReadWriteOnce    #单客户可读写
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "kafka-cluster"
  nfs:
    server: 192.168.188.81
    path: "/home/data/kafka"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-kafka2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "kafka-cluster"
  nfs:
    server: 192.168.188.82
    path: "/home/data/kafka"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-kafka3
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "kafka-cluster"
  nfs:
    server: 192.168.188.83
    path: "/home/data/kafka"


















