apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-zk1
spec:
  capacity:
    storage: 2000M      #磁盘大小2000M
  accessModes:
    - ReadWriteOnce    #单客户可读写
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "zookeeper-cluster"
  nfs:
    server: 192.168.188.81
    path: "/home/data/zk"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-zk2
spec:
  capacity:
    storage: 2000M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "zookeeper-cluster"
  nfs:
    server: 192.168.188.82
    path: "/home/data/zk"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-zk3
spec:
  capacity:
    storage: 2000M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "zookeeper-cluster"
  nfs:
    server: 192.168.188.83
    path: "/home/data/zk"


















